#!/usr/bin/env node
"use strict";Object.defineProperty(exports,"__esModule",{value:true});exports.default=exports.cli=exports.HELP_TEXT=void 0;var _index=require("../src/index.js");var _clipboardy=_interopRequireDefault(require("clipboardy"));function _interopRequireDefault(e){return e&&e.__esModule?e:{default:e}}function asyncGeneratorStep(n,t,e,r,o,a,c){try{var i=n[a](c),u=i.value}catch(n){return void e(n)}i.done?t(u):Promise.resolve(u).then(r,o)}function _asyncToGenerator(n){return function(){var t=this,e=arguments;return new Promise(function(r,o){var a=n.apply(t,e);function _next(n){asyncGeneratorStep(a,r,o,_next,_throw,"next",n)}function _throw(n){asyncGeneratorStep(a,r,o,_next,_throw,"throw",n)}_next(void 0)})}}var GENERIC_ERROR_CODE=1;var decode=/*#__PURE__*/function(){var _ref=_asyncToGenerator(function*(jwt){try{var decoded=yield(0,_index.jwtDecode)(jwt);return decoded}catch(e){throw e}});return function decode(_x){return _ref.apply(this,arguments)}}();var HELP_TEXT=exports.HELP_TEXT="******HELP*****\nuse -c or --clipboard or call command with no arguments to decode the JWT in your clipboard\nor call command with JWT as first argument\n****************";var cli=exports.cli=/*#__PURE__*/function(){var _ref2=_asyncToGenerator(function*(clipboard,argv){// read passed in argument
var arg2;var arg3;if(argv){arg2=argv[2];arg3=argv[3]}if(arg2=="-h"||arg2==="--help"){// Help display
console.log(HELP_TEXT);return HELP_TEXT}else if(arg2==="-c"||arg2==="--clipboard"||!arg2){// Check for something in the clipboard.
if(clipboard){// Great, there's something in the clipboard. Let's try to decode it as a
// JWT.
try{// Show what we found in the clipboard
console.log("Decoding: ");console.log(clipboard);var decoded=yield decode(clipboard);// Show the decoded jwt.
console.log(decoded);return decoded}catch(e){console.error("I found an error :(");console.error("Couldn't decode what was in your clipboard. You might try copying the JWT again.");console.error("What's the problem? ");console.error(" ",e.message);console.error("What's on your clipboard? ");console.error(" ",clipboard);return GENERIC_ERROR_CODE}}else{console.error("I found an error :(");console.error("Didn't find anything in your clipboard.");return GENERIC_ERROR_CODE}}else if(arg2==="-b"||arg2==="--base64url"){if(!arg3){console.error("I found an error :(");console.error("No argument passed in to encode.");return GENERIC_ERROR_CODE}try{var bases64urlified=(0,_index.base64URLEncode)(arg3);console.log(bases64urlified);return bases64urlified}catch(e){console.error("I found an error :(");console.error("base64url encoding failed:",e.message)}}else if(arg2){try{var _decoded=(0,_index.jwtDecode)(arg2);console.log("Decoding: \n"+arg2);console.log(_decoded);// return decoded;
}catch(e){console.error("I found an error :(.");// console.error(e, e.message);
console.error(e.message)}}else{console.error("I found an error :(.");console.error("Nothing in clipboard and no arguments given. Pass in a JWT as the first argument or copy a JWT to your clipboard")}});return function cli(_x2,_x3){return _ref2.apply(this,arguments)}}();// read from clipboard
var clipboard;try{clipboard=_clipboardy.default.readSync()}catch(e){clipboard=null}// read passed in argument
var argv=process.argv;cli(clipboard,argv);var _default=exports.default=cli;
